import {useState} from 'react';
import {api} from '../../services/api';
import {ErrorNotice,Field,FormActions,Modal,Select,TextArea} from './ui';
export default function EntityEditor({title,path,fields,item,onClose,onSaved,notify}){
  const [values,setValues]=useState(()=>Object.fromEntries(fields.map(f=>{let value=item?.[f.name]??f.default??(f.type==='checkbox'?false:'');if(f.type==='datetime-local'&&value){const dt=new Date(value);value=new Date(dt.getTime()-dt.getTimezoneOffset()*60000).toISOString().slice(0,16);}return [f.name,value];}))),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const set=(name,value)=>setValues(prev=>({...prev,[name]:value}));
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const body={};for(const f of fields){if(f.disabled)continue;const value=values[f.name];if(f.type==='number'||f.numeric)body[f.name]=value===''||value===null||value===undefined?null:Number(value);else if(f.type==='array')body[f.name]=Array.isArray(value)?value:String(value).split(',').map(s=>s.trim()).filter(Boolean);else if(f.type==='datetime-local')body[f.name]=value?new Date(value).toISOString():null;else body[f.name]=value;}await api(item?`${path}/${item.id}`:path,{method:item?'PUT':'POST',body});notify('Changes saved.');onSaved();onClose();}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <Modal title={title} onClose={onClose}><form onSubmit={submit}><div className="form-grid">{fields.map(f=><div className={f.type==='textarea'||f.full?'form-full':''} key={f.name}>{f.type==='select'?<Select label={f.label} options={f.options} placeholder={f.placeholder} required={f.required} disabled={f.disabled} value={values[f.name]??''} onChange={e=>set(f.name,f.numeric?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>:f.type==='textarea'?<TextArea label={f.label} required={f.required} disabled={f.disabled} value={values[f.name]} minLength={f.minLength} maxLength={f.maxLength||6000} onChange={e=>set(f.name,e.target.value)}/>:f.type==='checkbox'?<label className="checkbox"><input type="checkbox" checked={values[f.name]} disabled={f.disabled} onChange={e=>set(f.name,e.target.checked)}/>{f.label}</label>:<Field label={f.label} type={f.type==='array'?'text':f.type||'text'} required={f.required} disabled={f.disabled} minLength={f.minLength} min={f.min} max={f.max} step={f.step} maxLength={f.maxLength} hint={f.type==='array'?'Separate values with commas.':f.hint} value={f.type==='array'&&Array.isArray(values[f.name])?values[f.name].join(', '):f.type==='datetime-local'&&values[f.name]?String(values[f.name]).slice(0,16):values[f.name]??''} onChange={e=>set(f.name,e.target.value)}/>}</div>)}</div><ErrorNotice message={error}/><FormActions onCancel={onClose} busy={busy}/></form></Modal>;
}
