import {useState} from 'react';
import {ArrowRight,Boxes,CheckCircle2,Edit3,Plus} from 'lucide-react';
import {api} from '../../services/api';
import {Badge,Button,ErrorNotice,Field,FormActions,Modal,Panel,ResourceState,SectionTitle,Select,TextArea,date} from './ui';
import EntityEditor from './EntityEditor';
import ItemRows from './ItemRows';

const matching=(request,stock)=>request.item.trim().toLowerCase()===stock.item.trim().toLowerCase()&&(!request.unit||request.unit.trim().toLowerCase()===stock.unit.trim().toLowerCase())&&(!request.inventory_id||request.inventory_id===(stock.id||stock.inventory_id));
const delivered=(request,item)=>item.fulfilled_quantity??(request.distributions||[]).filter(row=>row.item?.trim().toLowerCase()===item.item.trim().toLowerCase()&&(!item.unit||row.unit?.trim().toLowerCase()===item.unit.trim().toLowerCase())).reduce((total,row)=>total+row.quantity,0);

export default function ReliefWorkspace({user,notify,requests,inventory,incidents,teams={data:[]},canDistribute,canComplete=false,saveRelief,navigate}){
  const isCitizen=user.role==='citizen',isAdmin=user.role==='admin';
  const [requestOpen,setRequestOpen]=useState(false),[inventoryEdit,setInventoryEdit]=useState(null),[distribution,setDistribution]=useState(null),[assignment,setAssignment]=useState(null),[completion,setCompletion]=useState(null),[kind,setKind]=useState('supplies');
  const [items,setItems]=useState([{item:'',quantity:1,unit:'units'}]),[location,setLocation]=useState(''),[incidentId,setIncidentId]=useState(''),[note,setNote]=useState(''),[stockId,setStockId]=useState(''),[quantity,setQuantity]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const inventoryFields=[{name:'item',label:'Item name',required:true,minLength:2,maxLength:100},{name:'quantity',label:'Stock quantity',type:'number',min:0,max:10000000,required:true},{name:'unit',label:'Unit',default:'units',required:true,minLength:1,maxLength:50},{name:'location',label:'Storage location',required:true,minLength:2,maxLength:200}];
  const stock=inventory.data.find(row=>row.id===Number(stockId)),requested=distribution?.items?.find(row=>stock&&matching(row,stock));
  const remaining=requested?Math.max(0,requested.quantity-delivered(distribution,requested)):0;
  const maximum=stock?Math.min(stock.quantity,remaining,100000):100000;
  function close(){setRequestOpen(false);setDistribution(null);setError('');setNote('');setStockId('');setQuantity(1);}
  async function submit(e){
    e.preventDefault();setBusy(true);setError('');
    try{
      if(!distribution&&kind==='supplies'&&new Set(items.map(row=>`${row.item.trim().toLowerCase()}:${(row.unit||'').trim().toLowerCase()}`)).size!==items.length)throw new Error('Combine repeated items with the same unit into one requested quantity.');
      if(distribution&&(!stock||!requested||Number(quantity)>maximum))throw new Error('Choose matching stock and a quantity within the remaining request and stock.');
      await saveRelief({distribution,stockId,quantity,note,items:kind==='rescue_support'?[]:items,location,incidentId,kind});
      notify(distribution?'Distribution recorded and stock updated.':'Relief request submitted.');
      requests.reload();inventory.reload();setItems([{item:'',quantity:1,unit:'units'}]);setLocation('');close();
    }catch(err){setError(err.message);}finally{setBusy(false);}
  }
  return <>
    <SectionTitle eyebrow="ESSENTIALS, WHERE THEY’RE NEEDED" title={isCitizen?'Relief & supplies':'Relief coordination'} description={isCitizen?'Request food, drinking water, medication, and other essentials.':'Assign requests and record distributions with matching stock units.'} action={isCitizen?<div className="inline">{navigate?<Button variant="secondary" onClick={()=>navigate('report')}>Request rescue support</Button>:null}<Button onClick={()=>{setRequestOpen(true);setError('');}}><Plus size={17}/>Request supplies</Button></div>:isAdmin?<Button onClick={()=>setInventoryEdit({})}><Plus size={17}/>Add inventory</Button>:null}/>
    {!isCitizen?<Panel title="Relief inventory" subtitle="Stock levels update as distributions are recorded."><ResourceState resource={inventory} emptyTitle="No inventory items" emptyBody="Add supplies to start tracking distributions."><div className="inventory-grid">{inventory.data.map(row=><div className="inventory-card" key={row.id}><Boxes size={20}/><div><strong>{row.item}</strong><small>{row.location}</small></div><span>{row.quantity}<small>{row.unit}</small></span>{isAdmin?<button className="icon-button" aria-label={`Edit ${row.item}`} onClick={()=>setInventoryEdit(row)}><Edit3 size={15}/></button>:null}</div>)}</div></ResourceState></Panel>:null}
    {isCitizen||canDistribute||canComplete?<Panel title={isCitizen?'Your supply requests':'Incoming requests'} subtitle="Each requested quantity and unit is tracked through distribution."><ResourceState resource={requests} emptyTitle="No relief requests" emptyBody={isCitizen?'Request essentials when your household needs support.':'Assigned citizen requests will appear here.'}><div className="request-list">{requests.data.map(request=><article className="relief-request" key={request.id}><div className="request-header"><span className="request-symbol"><Boxes size={21}/></span><div><strong>Relief request #{request.id}</strong><small>{request.location} · {date(request.created_at)}</small></div><Badge value={request.kind==='rescue_support'?'rescue':'supplies'}/><Badge value={request.status||'pending'}/></div><div className="requested-items">{request.items?.map((item,index)=><span key={index}><strong>{item.quantity}</strong> {item.unit||'units'} {item.item}<small>{delivered(request,item)} distributed</small></span>)}</div>{request.note?<p>{request.note}</p>:null}{request.assignment?<p className="muted">Assigned to {request.assignment.team_name||`team #${request.assignment.team_id}`} · {date(request.assignment.assigned_at||request.assignment.created_at)}</p>:null}{request.distributions?.length?<div className="distribution-notes">{request.distributions.map((row,index)=><small key={row.id||index}><CheckCircle2 size={12}/>{row.quantity} {row.unit||'units'} {row.item||'items'} distributed · {date(row.created_at)}</small>)}</div>:null}<div className="action-row">{isAdmin&&!['fulfilled','completed'].includes(request.status)?<Button variant="secondary small" onClick={()=>setAssignment(request)}>{request.kind==='rescue_support'?'Assign rescue team':'Assign relief team'}</Button>:null}{(isAdmin||canComplete)&&request.kind==='rescue_support'&&!['fulfilled','completed'].includes(request.status)?<Button variant="secondary small" onClick={()=>setCompletion(request)}>Complete rescue support</Button>:null}{canDistribute&&request.kind!=='rescue_support'&&!['fulfilled','completed'].includes(request.status)?<Button variant="secondary small" onClick={()=>{setDistribution(request);setError('');}}>Record distribution<ArrowRight size={14}/></Button>:null}</div></article>)}</div></ResourceState></Panel>:<Panel title="Relief team coordination"><p className="muted">Relief requests are handled by the coordinator and assigned relief teams. Available inventory is shown above for response planning.</p></Panel>}
    {inventoryEdit?<EntityEditor title={inventoryEdit.id?'Update inventory':'Add inventory'} path="/relief/inventory" fields={inventoryFields} item={inventoryEdit.id?inventoryEdit:null} onClose={()=>setInventoryEdit(null)} onSaved={inventory.reload} notify={notify}/>:null}
    {assignment?<AssignRelief request={assignment} teams={teams.data} onClose={()=>setAssignment(null)} onSaved={requests.reload} notify={notify}/>:null}
    {completion?<CompleteRescue request={completion} onClose={()=>setCompletion(null)} onSaved={requests.reload} notify={notify}/>:null}{requestOpen||distribution?<Modal title={distribution?'Record a supply distribution':'Request relief supplies'} onClose={close}><form onSubmit={submit}>{distribution?<><p className="muted">Request #{distribution.id} · {distribution.location}. Item names and units must match.</p><Select label="Inventory item" required placeholder="Choose matching available stock" value={stockId} onChange={e=>{setStockId(e.target.value);setQuantity(1);}} options={inventory.data.filter(row=>row.quantity>0&&distribution.items?.some(item=>matching(item,row)&&item.quantity>delivered(distribution,item))).map(row=>({value:row.id,label:`${row.item} · ${row.quantity} ${row.unit} available`}))}/><Field label="Quantity distributed" type="number" min={1} max={maximum||1} required value={quantity} onChange={e=>setQuantity(e.target.value)}/>{stock?<p className="fine-print">Up to {maximum} {stock.unit}: {remaining} still requested; {stock.quantity} in stock.</p>:null}</>:<><Select label="Type of support" options={[{value:'supplies',label:'Food, water, medicine or supplies'},{value:'rescue_support',label:'Rescue support'}]} value={kind} onChange={e=>setKind(e.target.value)}/>{kind==='supplies'?<ItemRows items={items} setItems={setItems} units catalog={inventory.data}/>:<p className="fine-print">A coordinator will assign a rescue team. In immediate danger, call 112.</p>}<Field label="Delivery location / landmark" required minLength={2} value={location} onChange={e=>setLocation(e.target.value)} maxLength={200}/><Select label="Related report (optional)" value={incidentId} onChange={e=>setIncidentId(e.target.value)} placeholder="No related report" options={incidents.data.map(row=>({value:row.id,label:`${row.reference||row.id} · ${row.location}`}))}/></>}<TextArea label="Additional note" value={note} onChange={e=>setNote(e.target.value)} maxLength={2000}/><ErrorNotice message={error}/><FormActions busy={busy} label={distribution?'Record distribution':'Submit request'} onCancel={close}/></form></Modal>:null}
  </>;
}
function AssignRelief({request,teams,onClose,onSaved,notify}){
  const [team,setTeam]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function assign(e){e.preventDefault();setBusy(true);setError('');try{await api(`/relief/requests/${request.id}/assign`,{method:'POST',body:{team_id:Number(team),note}});notify('Relief request assigned. The team can now record delivery.');onSaved();onClose();}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <Modal title={`Assign relief request #${request.id}`} onClose={onClose}><form onSubmit={assign}><Select label={request.kind==='rescue_support'?'Rescue team':'Relief team'} required placeholder="Choose an available response team" options={teams.filter(row=>row.team_type===(request.kind==='rescue_support'?'rescue':'relief')&&row.available).map(row=>({value:row.id,label:row.name}))} value={team} onChange={e=>setTeam(e.target.value)}/><TextArea label="Assignment note" required minLength={2} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/><ErrorNotice message={error}/><FormActions label="Assign relief request" busy={busy} onCancel={onClose}/></form></Modal>;
}
function CompleteRescue({request,onClose,onSaved,notify}){
  const [note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function complete(e){e.preventDefault();setBusy(true);setError('');try{await api(`/relief/requests/${request.id}/complete`,{method:'POST',body:{note}});notify('Rescue support recorded as completed.');onSaved();onClose();}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <Modal title={`Complete rescue request #${request.id}`} onClose={onClose}><form onSubmit={complete}><TextArea label="Rescue completion note" required minLength={2} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/><ErrorNotice message={error}/><FormActions busy={busy} label="Complete rescue support" onCancel={onClose}/></form></Modal>;
}

