import {useEffect,useId,useRef} from 'react';
import {AlertCircle,ArrowRight,Check,ChevronRight,LoaderCircle,MapPin,Search,X} from 'lucide-react';
export const districts = ['Alappuzha','Ernakulam','Idukki','Kannur','Kasaragod','Kollam','Kottayam','Kozhikode','Malappuram','Palakkad','Pathanamthitta','Thiruvananthapuram','Thrissur','Wayanad'];
export const label = value => String(value || 'unknown').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
export function date(value) { if (!value) return '—'; const dt = new Date(value); return Number.isNaN(dt.valueOf()) ? String(value) : dt.toLocaleString('en-IN', {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}); }

export function Badge({value,children}) {return <span className={`badge badge-${String(value||'').toLowerCase()}`}>{children||label(value)}</span>;}
export function Button({children,variant='',busy=false,...props}) {return <button className={`button ${variant}`} {...props} disabled={props.disabled || busy}>{busy ? <LoaderCircle size={16} className="spin"/> : null}{children}</button>;}
export function Field({label: title,children,hint,...props}) {const id=useId();return <label className="field" htmlFor={id}><span>{title}</span>{children ? children : <input id={id} {...props}/ >}{hint?<small>{hint}</small>:null}</label>;}
export function Select({label:title,options,placeholder,...props}) {const id=useId();return <label className="field" htmlFor={id}><span>{title}</span><select id={id} aria-label={title} {...props}>{placeholder?<option value="">{placeholder}</option>:null}{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select></label>;}
export function TextArea({label:title,...props}) {const id=useId();return <label className="field" htmlFor={id}><span>{title}</span><textarea id={id} rows={4} {...props}/></label>;}
export function ErrorNotice({message,onRetry}) {return message?<div className="error-notice" role="alert"><AlertCircle size={18}/><span>{message}</span>{onRetry?<button onClick={onRetry}>Retry</button>:null}</div>:null;}
export function Empty({title='Nothing here yet',body='New information will appear here.',action}) {return <div className="empty"><div className="empty-symbol"><Check size={24}/></div><h3>{title}</h3><p>{body}</p>{action}</div>;}
export function Loading() {return <div className="loading"><LoaderCircle size={22} className="spin"/> Loading information…</div>;}
export function ResourceState({resource,children,emptyTitle,emptyBody}) {if(resource.loading) return <Loading/>;return <><ErrorNotice message={resource.error} onRetry={resource.reload}/>{resource.data?.length === 0 ? <Empty title={emptyTitle} body={emptyBody}/> : children}</>;}
export function SectionTitle({eyebrow,title,description,action}) {return <div className="section-heading"><div>{eyebrow?<span className="eyebrow">{eyebrow}</span>:null}<h1>{title}</h1>{description?<p>{description}</p>:null}</div>{action}</div>;}
export function Panel({title,subtitle,action,children,className=''}) {return <section className={`panel ${className}`}>{title?<div className="panel-heading"><div><h2>{title}</h2>{subtitle?<p>{subtitle}</p>:null}</div>{action}</div>:null}{children}</section>;}
export function SearchBox({value,onChange,placeholder='Search…'}) {return <div className="search-box"><Search size={18}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>;}
export function shelterAvailable(item) {return item.status&&item.status!=='open'?0:item.available_capacity??Math.max(0,item.capacity-item.occupied);}
export function Location({item}) {const url=item.latitude!=null&&item.longitude!=null?`https://www.openstreetmap.org/?mlat=${encodeURIComponent(item.latitude)}&mlon=${encodeURIComponent(item.longitude)}#map=15/${encodeURIComponent(item.latitude)}/${encodeURIComponent(item.longitude)}`:`https://www.openstreetmap.org/search?query=${encodeURIComponent(`${item.location||''} ${item.district||''} Kerala`)}`;return <a className="location" href={url} target="_blank" rel="noreferrer"><MapPin size={14}/>{item.location || item.district || 'Location pending'}<ChevronRight size={12}/></a>;}
export function Modal({title,onClose,children,wide=false}) {
  const ref=useRef(null),closeRef=useRef(onClose),id=useId();
  closeRef.current=onClose;
  useEffect(()=>{const prev=document.activeElement;ref.current?.focus();const close=e=>{if(e.key==='Escape') closeRef.current();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',close);return()=>{document.removeEventListener('keydown',close);prev?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className={`modal ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-labelledby={id} tabIndex={-1} ref={ref}><div className="modal-heading"><h2 id={id}>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</section></div>;
}
export function Stat({title,value,icon:Icon,detail,tone=''}) {return <div className={`stat ${tone}`}><div className="stat-top"><span>{title}</span><Icon size={19}/></div><strong>{value ?? '—'}</strong>{detail?<small>{detail}</small>:null}</div>;}
export function ActionLink({children,onClick}) {return <button className="text-button" onClick={onClick}>{children}<ArrowRight size={15}/></button>;}
export function FormActions({onCancel,busy,label:caption='Save changes'}) {return <div className="form-actions">{onCancel?<Button variant="secondary" type="button" onClick={onCancel}>Cancel</Button>:null}<Button type="submit" busy={busy}>{caption}</Button></div>;}
