import {useState} from 'react';
import {CheckCircle2,Edit3,Tent} from 'lucide-react';
import {Badge,Empty,Location,ResourceState,SearchBox,SectionTitle,districts,label,shelterAvailable} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';
export default function ShelterManagement({user,notify}){
  const resource=useData('/shelters',{poll:20000}),[search,setSearch]=useState(''),[district,setDistrict]=useState(''),[editor,setEditor]=useState(null);
  const list=resource.data.filter(s=>[s.name,s.location,s.district].join(' ').toLowerCase().includes(search.toLowerCase())&&(!district||s.district===district));
  const fields=[{name:'status',label:'Shelter status',type:'select',options:['open','full','closed'],default:'open',required:true},{name:'occupied',label:'Current occupancy',type:'number',min:0,max:100000,default:0,required:true},{name:'facilities',label:'Facilities',type:'array',default:[],full:true}];
  return <><SectionTitle eyebrow="A SAFER PLACE TO STAY" title="Shelters & available spaces" description="Search community shelter listings. Contact the coordinator to confirm access and availability." /><div className="page-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search a shelter or location"/><select aria-label="Filter shelters by district" value={district} onChange={e=>setDistrict(e.target.value)}><option value="">All districts</option>{districts.map(d=><option key={d}>{d}</option>)}</select><span className="muted">{list.reduce((n,s)=>n+shelterAvailable(s),0)} spaces across {list.length} shelters</span></div><ResourceState resource={resource} emptyTitle="No shelters listed" emptyBody="Shelter listings will appear when published by the coordinator."><div className="shelter-grid">{list.map(s=>{const available=shelterAvailable(s);return <article className="shelter-card panel" key={s.id}><div className="card-top"><span className="shelter-symbol"><Tent size={27}/></span><Badge value={s.status==='closed'?'closed':available?'available':'full'}>{s.status==='closed'?'Closed':available?'Spaces available':'At capacity'}</Badge>{user.team_id&&s.team_id===user.team_id?<button className="icon-button" aria-label={`Edit ${s.name}`} onClick={()=>setEditor(s)}><Edit3 size={16}/></button>:null}</div><span className="eyebrow">{s.district}</span><h2>{s.name}</h2><Location item={s}/><div className="shelter-capacity"><strong>{available}<small>spaces available</small></strong><span>{s.occupied} / {s.capacity}<small>currently occupied</small></span></div><div className="capacity-meter"><i style={{width:`${Math.min(100,s.occupied/s.capacity*100)}%`}}/></div><div className="facilities">{s.facilities?.map(f=><span key={f}><CheckCircle2 size={12}/>{f}</span>)}</div><small className="muted">Demo listing · Confirm before travelling</small></article>;})}</div>{resource.data.length&&!list.length?<Empty title="No shelters match" body="Search another location or district."/>:null}</ResourceState>{editor?<EntityEditor title={editor.id?'Update shelter':'Add shelter'} path="/shelters" fields={fields} item={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}</>;
}
