import {useState} from 'react';
import {Edit3,Plus,Shield} from 'lucide-react';
import {Badge,Button,Empty,Location,ResourceState,SearchBox,SectionTitle,date,districts,label} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';
const districtField={name:'district',label:'District',type:'select',options:districts,default:'Ernakulam',required:true};
const activeField={name:'active',label:'Active',type:'checkbox',default:true};
const alertFields=[{name:'title',label:'Alert title',required:true,minLength:3,maxLength:160},{name:'severity',label:'Severity',type:'select',options:['high','moderate','low'],default:'moderate'},{name:'message',label:'Alert message',type:'textarea',required:true,minLength:5},{name:'location',label:'Location',required:true,minLength:2,maxLength:200},districtField,{name:'expires_at',label:'Expires at',type:'datetime-local'},activeField];
export default function Alerts({user,notify}){
  const resource=useData(user.role==='admin'?'/admin/alerts':'/alerts'),[search,setSearch]=useState(''),[editor,setEditor]=useState(null),[showAll,setShowAll]=useState(false),isAdmin=user.role==='admin';
  const list=resource.data.filter(a=>[a.title,a.location,a.district].join(' ').toLowerCase().includes(search.toLowerCase())&&(showAll||a.active!==false&&(!a.expires_at||new Date(a.expires_at)>new Date())));
  return <><SectionTitle eyebrow="KNOW WHAT’S HAPPENING" title="Flood alerts" description="Coordinator-published alerts for your community. These are demonstration listings." action={isAdmin?<Button onClick={()=>setEditor({})}><Plus size={17}/>Create alert</Button>:null}/><div className="page-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search by place or district"/>{isAdmin?<label className="checkbox"><input type="checkbox" checked={showAll} onChange={e=>setShowAll(e.target.checked)}/>Include inactive alerts</label>:null}</div><ResourceState resource={resource} emptyTitle="No alerts published" emptyBody="Follow official local announcements for current conditions."><div className="alerts-grid">{list.map(a=><article className={`alert-card ${a.severity}`} key={a.id}><div className="card-top"><span className="alert-icon"><Shield size={22}/></span><Badge value={a.severity}/>{isAdmin?<button className="icon-button" aria-label={`Edit ${a.title}`} onClick={()=>setEditor(a)}><Edit3 size={16}/></button>:null}</div><span className="eyebrow">{a.district}</span><h2>{a.title}</h2><p>{a.message}</p><div className="alert-card-footer"><Location item={a}/><span>{a.active===false?'Inactive':a.expires_at?`Until ${date(a.expires_at)}`:'Active until updated'}</span></div></article>)}</div>{resource.data.length&&!list.length?<Empty title="No matching alerts" body="Try another place or include inactive alerts."/>:null}</ResourceState>{editor?<EntityEditor title={editor.id?'Edit flood alert':'Create flood alert'} path="/alerts" fields={alertFields} item={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}</>;
}
