import {useState} from 'react';
import {Edit3,HeartHandshake,Plus} from 'lucide-react';
import {api} from '../../services/api';
import {Badge,Button,ErrorNotice,Field,Modal,Panel,ResourceState,SectionTitle,TextArea,date} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';
const support=pledge=>pledge.kind==='money'?`₹${Number(pledge.amount).toLocaleString('en-IN')}`:pledge.items?.map(item=>`${item.quantity} ${item.unit||'units'} ${item.item}`).join(', ');
export default function Donations({notify}){
  const resource=useData('/admin/campaigns'),pledges=useData('/donations/pledges',{poll:15000}),records=useData('/donations/records');
  const [editor,setEditor]=useState(null),[verification,setVerification]=useState(null);
  const fields=[{name:'title',label:'Campaign title',required:true,minLength:3,maxLength:160},{name:'description',label:'Description',type:'textarea',required:true,minLength:5,maxLength:6000},{name:'target_amount',label:'Donation target (₹)',type:'number',min:0,max:100000000,step:'0.01',default:0},{name:'active',label:'Active',type:'checkbox',default:true}];
  function saved(){pledges.reload();records.reload();resource.reload();}
  return <>
    <SectionTitle eyebrow="SMALL ACTS. SHARED STRENGTH." title="Support campaigns" description="Manage campaigns, verify transfers and supply handovers, and issue accountable donation receipts." action={<Button onClick={()=>setEditor({})}><Plus size={17}/>Create campaign</Button>}/>
    <ResourceState resource={resource} emptyTitle="No campaigns yet"><div className="campaign-grid">{resource.data.map(campaign=><article className="campaign-card panel" key={campaign.id}><div className="campaign-art"><HeartHandshake size={48}/><span>TOGETHER, FOR KERALA</span></div><div className="campaign-body"><div className="inline"><Badge value={campaign.active?'active':'closed'}/><button className="icon-button" aria-label={`Edit ${campaign.title}`} onClick={()=>setEditor(campaign)}><Edit3 size={15}/></button></div><h2>{campaign.title}</h2><p>{campaign.description}</p><div className="campaign-target"><strong>₹{Number(campaign.received_amount||0).toLocaleString('en-IN')}<small>verified receipts</small></strong><span>₹{Number(campaign.target_amount).toLocaleString('en-IN')}<small>target</small></span></div><p className="fine-print">₹{Number(campaign.pledged_amount||campaign.total_pledged||0).toLocaleString('en-IN')} committed. Test-mode receipts are identified separately.</p></div></article>)}</div></ResourceState>
    <Panel title="Donation verification queue" subtitle="A donor reference is a claim until the coordinator checks actual receipt."><ResourceState resource={pledges} emptyTitle="No donations submitted"><div className="request-list">{pledges.data.map(pledge=><article className="relief-request" key={pledge.id}><div className="request-header"><div><strong>Donation #{pledge.id} · {pledge.campaign_title||resource.data.find(row=>row.id===pledge.campaign_id)?.title||`Campaign #${pledge.campaign_id}`}</strong><small>{date(pledge.created_at)}</small></div><Badge value={pledge.status}/></div><p>{support(pledge)}</p>{pledge.proof_reference?<p>Claimed {pledge.proof_method}: {pledge.proof_reference}</p>:null}{pledge.proof_note?<p>{pledge.proof_note}</p>:null}{pledge.status==='pending_verification'?<Button variant="secondary small" onClick={()=>setVerification(pledge)}>Review donation receipt</Button>:pledge.receipt?<p className="fine-print">Receipt #{pledge.receipt.id} · {pledge.receipt.reference}</p>:<p className="muted">No receipt issued.</p>}</article>)}</div></ResourceState></Panel>
    <Panel title="Verified donation receipts" subtitle="Persisted receipts from checked handovers or provider-confirmed payments."><ResourceState resource={records} emptyTitle="No verified receipts"><div className="table-scroll"><table><thead><tr><th>Receipt</th><th>Donation</th><th>Received support</th><th>Method / reference</th><th>Confirmation</th></tr></thead><tbody>{records.data.map(receipt=><tr key={receipt.id}><td>#{receipt.id}</td><td>#{receipt.pledge_id}</td><td>{support(receipt)}</td><td>{receipt.method}<small>{receipt.reference}</small></td><td>{date(receipt.created_at)}{receipt.sandbox?<small>Sandbox · no real funds transferred</small>:<small>Verified receipt</small>}</td></tr>)}</tbody></table></div></ResourceState></Panel>
    {editor?<EntityEditor title={editor.id?'Edit campaign':'Create campaign'} path="/donations/campaigns" fields={fields} item={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}
    {verification?<VerifyDonation pledge={verification} onClose={()=>setVerification(null)} onSaved={saved} notify={notify}/>:null}
  </>;
}
function VerifyDonation({pledge,onClose,onSaved,notify}){
  const [reference,setReference]=useState(pledge.proof_reference||''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
  async function verify(approved){if(approved&&!confirmed)return;if(!approved&&note.trim().length<3){setError('Record why this donation reference is rejected.');return;}setBusy(approved?'approve':'reject');setError('');try{await api(`/donations/${pledge.id}/verify`,{method:'POST',body:{approved,reference,note}});notify(approved?'Verified donation receipt issued.':'Donation reference rejected.');onSaved();onClose();}catch(err){setError(err.message);}finally{setBusy('');}}
  return <Modal title={`Review donation #${pledge.id}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();verify(true);}}><p>{support(pledge)} · {pledge.proof_method}</p><p>Donor reference: {pledge.proof_reference}</p><Field label="Verified receipt reference" required minLength={3} maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/><TextArea label="Verification note" maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/><label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked that the money or supplies were actually received.</label><ErrorNotice message={error}/><div className="form-actions"><Button type="button" variant="secondary" onClick={()=>verify(false)} busy={busy==='reject'}>Reject reference</Button><Button type="submit" disabled={!confirmed||reference.trim().length<3} busy={busy==='approve'}>Issue verified receipt</Button></div></form></Modal>;
}
