import {useState} from 'react';
import {Edit3,Plus,ShieldCheck} from 'lucide-react';
import {api} from '../../services/api';
import {Badge,Button,ErrorNotice,ResourceState,SectionTitle,date} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';
const newsFields=[{name:'title',label:'Headline',required:true,minLength:3,maxLength:160},{name:'content',label:'News content',type:'textarea',required:true,minLength:5,maxLength:10000},{name:'source',label:'Source',default:'ResQ coordination desk',maxLength:250}];
export default function News({user,notify,navigate}){
  const resource=useData('/admin/news'),[editor,setEditor]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
  async function action(item,operation){setBusy(`${item.id}-${operation}`);setError('');try{await api(operation==='verify'?`/news/${item.id}/verify`:`/news/${item.id}`,{method:operation==='verify'?'POST':'PUT',body:operation==='verify'?{note:'Reviewed by the coordinator before publication.'}:{published:operation==='publish'}});notify(operation==='verify'?'News verified. It is ready for publication.':operation==='publish'?'Verified news published.':'News returned to draft.');resource.reload();}catch(err){setError(err.message);}finally{setBusy('');}}
  return <><SectionTitle eyebrow="FROM THE COORDINATION DESK" title="Community news" description="Review and verify each update before publishing it to the community." action={<div className="inline"><Button variant="secondary" onClick={()=>navigate('safety')}>Manage safety guidance</Button><Button onClick={()=>setEditor({})}><Plus size={17}/>Write an update</Button></div>}/><ErrorNotice message={error}/><ResourceState resource={resource} emptyTitle="No news published yet" emptyBody="Updates from the coordination desk appear here."><div className="news-grid">{resource.data.map((item,index)=><article className={`news-card panel ${index===0?'featured':''}`} key={item.id}><div className="card-top"><span className="eyebrow">COMMUNITY UPDATE</span><div className="inline"><Badge value={item.verified?'verified':'under_review'}>{item.verified?'Verified':'Awaiting verification'}</Badge><Badge value={item.published?'published':'draft'}/><button className="icon-button" aria-label={`Edit ${item.title}`} onClick={()=>setEditor(item)}><Edit3 size={16}/></button></div></div><h2>{item.title}</h2><p className="article-content">{item.content}</p><div className="article-meta"><span>{item.source||'ResQ coordination desk'}</span><span>{date(item.created_at)}</span></div><div className="action-row">{!item.verified?<Button variant="secondary small" busy={busy===`${item.id}-verify`} onClick={()=>action(item,'verify')}><ShieldCheck size={15}/>Verify update</Button>:null}{!item.published?<Button variant="secondary small" disabled={!item.verified} busy={busy===`${item.id}-publish`} onClick={()=>action(item,'publish')}>Publish verified update</Button>:<Button variant="secondary small" busy={busy===`${item.id}-unpublish`} onClick={()=>action(item,'unpublish')}>Return to draft</Button>}</div></article>)}</div></ResourceState>{editor?<EntityEditor title={editor.id?'Edit community update':'Write community update'} path="/news" fields={newsFields} item={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}</>;
}
