import {useState} from 'react';
import {Edit3,Plus,ShieldCheck} from 'lucide-react';
import {Button,ResourceState,SectionTitle,label} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';
const safetyFields=[{name:'title',label:'Guidance title',required:true,minLength:3,maxLength:160},{name:'content',label:'Safety guidance',type:'textarea',required:true,minLength:5},{name:'category',label:'Category',default:'flood',maxLength:50},{name:'source',label:'Source attribution',default:'Project safety guidance',maxLength:250}];
export default function Safety({user,notify}){
  const resource=useData('/safety-tips'),[editor,setEditor]=useState(null),isAdmin=user.role==='admin';
  return <><SectionTitle eyebrow="PREPARE. PROTECT. STAY INFORMED." title="Flood safety guidance" description="Practical safety information from the project knowledge base. Follow local official advice." action={isAdmin?<Button onClick={()=>setEditor({})}><Plus size={17}/>Add guidance</Button>:null}/><div className="safety-banner"><ShieldCheck size={29}/><div><h2>In immediate danger, call 112.</h2><p>Never enter floodwater to take a photograph or submit a report.</p></div></div><ResourceState resource={resource} emptyTitle="No guidance published" emptyBody="Safety guidance appears here when added by the coordinator."><div className="safety-grid">{resource.data.map((tip,index)=><article className="safety-card panel" key={tip.id||tip.title}><div className="card-top"><span className="safety-number">{String(index+1).padStart(2,'0')}</span><span className="eyebrow">{tip.category||'FLOOD SAFETY'}</span>{isAdmin?<button className="icon-button" aria-label={`Edit ${tip.title}`} onClick={()=>setEditor(tip)}><Edit3 size={15}/></button>:null}</div><h2>{tip.title}</h2><p className="article-content">{tip.content}</p><small>Source: {tip.source||'Project safety guidance'}</small></article>)}</div></ResourceState>{editor?<EntityEditor title={editor.id?'Edit safety guidance':'Add safety guidance'} path="/safety-tips" fields={safetyFields} item={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}</>;
}
