import {useState} from 'react';
import {CheckCircle2,Edit3,Plus,Tent} from 'lucide-react';
import {Badge,Button,Empty,Location,ResourceState,SearchBox,SectionTitle,districts,label,shelterAvailable} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';
const districtField={name:'district',label:'District',type:'select',options:districts,default:'Ernakulam',required:true};
export default function Shelters({user,notify}){
  const resource=useData('/shelters',{poll:20000}),teams=useData(user.role==='admin'?'/teams':null),[search,setSearch]=useState(''),[district,setDistrict]=useState(''),[editor,setEditor]=useState(null),isAdmin=user.role==='admin';
  const list=resource.data.filter(s=>[s.name,s.location,s.district].join(' ').toLowerCase().includes(search.toLowerCase())&&(!district||s.district===district));
  const fields=[{name:'status',label:'Shelter status',type:'select',options:['open','full','closed'],default:'open',required:true},{name:'name',label:'Shelter name',required:true,minLength:3,maxLength:160},{name:'location',label:'Location / landmark',required:true,minLength:2,maxLength:200},districtField,{name:'capacity',label:'Total capacity',type:'number',min:1,max:100000,required:true},{name:'occupied',label:'Current occupancy',type:'number',min:0,max:100000,default:0,required:true},{name:'facilities',label:'Facilities',type:'array',default:[],full:true},{name:'latitude',label:'Latitude',type:'number',step:'any',min:-90,max:90},{name:'longitude',label:'Longitude',type:'number',step:'any',min:-180,max:180},{name:'team_id',label:'Responsible shelter team',type:'select',numeric:true,placeholder:'Unassigned',options:teams.data.filter(t=>t.team_type==='shelter').map(t=>({value:t.id,label:t.name})),default:null}];
  return <><SectionTitle eyebrow="A SAFER PLACE TO STAY" title="Shelters & available spaces" description="Search community shelter listings. Contact the coordinator to confirm access and availability." action={isAdmin?<Button onClick={()=>setEditor({})}><Plus size={17}/>Add shelter</Button>:null}/><div className="page-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search a shelter or location"/><select aria-label="Filter shelters by district" value={district} onChange={e=>setDistrict(e.target.value)}><option value="">All districts</option>{districts.map(d=><option key={d}>{d}</option>)}</select><span className="muted">{list.reduce((n,s)=>n+shelterAvailable(s),0)} spaces across {list.length} shelters</span></div><ResourceState resource={resource} emptyTitle="No shelters listed" emptyBody="Shelter listings will appear when published by the coordinator."><div className="shelter-grid">{list.map(s=>{const available=shelterAvailable(s);return <article className="shelter-card panel" key={s.id}><div className="card-top"><span className="shelter-symbol"><Tent size={27}/></span><Badge value={s.status==='closed'?'closed':available?'available':'full'}>{s.status==='closed'?'Closed':available?'Spaces available':'At capacity'}</Badge>{isAdmin||user.team_id&&s.team_id===user.team_id?<button className="icon-button" aria-label={`Edit ${s.name}`} onClick={()=>setEditor(s)}><Edit3 size={16}/></button>:null}</div><span className="eyebrow">{s.district}</span><h2>{s.name}</h2><Location item={s}/><div className="shelter-capacity"><strong>{available}<small>spaces available</small></strong><span>{s.occupied} / {s.capacity}<small>currently occupied</small></span></div><div className="capacity-meter"><i style={{width:`${Math.min(100,s.occupied/s.capacity*100)}%`}}/></div><div className="facilities">{s.facilities?.map(f=><span key={f}><CheckCircle2 size={12}/>{f}</span>)}</div><small className="muted">Demo listing · Confirm before travelling</small></article>;})}</div>{resource.data.length&&!list.length?<Empty title="No shelters match" body="Search another location or district."/>:null}</ResourceState>{editor?<EntityEditor title={editor.id?'Update shelter':'Add shelter'} path="/shelters" fields={isAdmin?fields:fields.filter(f=>['occupied','facilities'].includes(f.name))} item={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}</>;
}
