import {useState} from 'react';
import {Edit3,LifeBuoy,Plus,Shield,Tent,Truck,Users} from 'lucide-react';
import {api} from '../../services/api';
import {Badge,Button,ResourceState,SearchBox,SectionTitle,districts,label} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';

const teamIcons={rescue:LifeBuoy,investigation:Shield,relief:Truck,shelter:Tent};
export default function Teams({notify}){
  const resource=useData('/teams',{poll:20000}),[editor,setEditor]=useState(null),[search,setSearch]=useState(''),[busy,setBusy]=useState(null);
  const fields=[{name:'name',label:'Team name',required:true,minLength:2,maxLength:120},{name:'team_type',label:'Team type',type:'select',options:['rescue','investigation','relief','shelter'],default:'rescue'}, {name:'district',label:'District',type:'select',options:districts,default:'Ernakulam'},{name:'available',label:'Available for assignments',type:'checkbox',default:true}];
  const teams=resource.data.filter(t=>[t.name,t.team_type,t.district].join(' ').toLowerCase().includes(search.toLowerCase()));
  return <><SectionTitle eyebrow="PEOPLE WHO SHOW UP" title="Response teams" description="Manage team responsibilities, district coverage, and readiness for new assignments." action={<Button onClick={()=>setEditor({})}><Plus size={17}/>Create a team</Button>}/><div className="page-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search teams, types or districts"/><span className="muted">{resource.data.filter(t=>t.available).length} teams available</span></div><ResourceState resource={resource} emptyTitle="No teams yet" emptyBody="Register your first team to start coordinating assignments."><div className="teams-grid">{teams.map(t=>{const Icon=teamIcons[t.team_type]||Users;return <article className="team-card panel" key={t.id}><div className="card-top"><span className={`team-symbol ${t.team_type}`}><Icon size={25}/></span><Badge value={t.available?'available':'busy'}/><button className="icon-button" onClick={()=>setEditor(t)} aria-label={`Edit ${t.name}`}><Edit3 size={16}/></button></div><span className="eyebrow">{label(t.team_type)} TEAM</span><h2>{t.name}</h2><p>{t.district}</p><div className="team-meta"><span><Users size={14}/>District response team</span><span>{t.available?'Ready for assignment':'Availability restricted'}</span></div><Button variant="secondary full-width" busy={busy===t.id} onClick={async()=>{setBusy(t.id);try{await api(`/teams/${t.id}`,{method:'PUT',body:{available:!t.available}});resource.reload();notify('Team availability updated.');}catch(e){notify(e.message,'error');}finally{setBusy(null);}}}>{t.available?'Mark unavailable':'Mark available'}</Button></article>;})}</div></ResourceState>{editor?<EntityEditor title={editor.id?'Edit response team':'Create response team'} path="/teams" fields={fields} item={editor.id?editor:null} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}</>;
}
