import {useState} from 'react';
import {Edit3,Plus} from 'lucide-react';
import {api} from '../../services/api';
import {Badge,Button,ErrorNotice,Field,FormActions,Modal,Panel,ResourceState,SearchBox,SectionTitle,Select,districts,label,date} from '../../components/shared/ui';
import EntityEditor from '../../components/shared/EntityEditor';
import {useData} from '../../hooks/useData';

export default function UsersPage({user,notify}){
  const resource=useData('/admin/users'),teams=useData('/teams'),[search,setSearch]=useState(''),[editor,setEditor]=useState(null),[createOpen,setCreateOpen]=useState(false);
  const fields=[{name:'active',label:'Account active',type:'checkbox',default:true},{name:'role',label:'Account role',type:'select',options:[{value:'citizen',label:'Citizen'},{value:'response_team',label:'Response team'},{value:'admin',label:'Coordinator / admin'}],default:'citizen'},{name:'team_id',label:'Assigned team',type:'select',numeric:true,placeholder:'No team',options:teams.data.map(t=>({value:t.id,label:`${t.name} · ${label(t.team_type)}`})),default:null}];
  const list=resource.data.filter(u=>[u.name,u.email,u.role,u.district].join(' ').toLowerCase().includes(search.toLowerCase()));
  return <><SectionTitle eyebrow="ACCESS WITH ACCOUNTABILITY" title="People & permissions" description="Manage account access and connect response members to the right team." action={<Button onClick={()=>setCreateOpen(true)}><Plus size={17}/>Add a team member</Button>}/><Panel><div className="table-toolbar"><SearchBox value={search} onChange={setSearch} placeholder="Search names, email or role"/><span className="muted">{resource.data.length} accounts</span></div><ResourceState resource={resource} emptyTitle="No accounts found"><div className="table-scroll"><table><thead><tr><th>Person</th><th>Role</th><th>District / team</th><th>Access</th><th/></tr></thead><tbody>{list.map(u=><tr key={u.id}><td><div className="person-cell"><span className="avatar light">{u.name.slice(0,1)}</span><div><strong>{u.name}</strong><small>{u.email}</small></div></div></td><td><Badge value={u.role}/></td><td>{u.district}<small>{teams.data.find(t=>t.id===u.team_id)?.name||'No team assigned'}</small></td><td><Badge value={u.active?'active':'inactive'}/></td><td><Button variant="secondary small" disabled={u.id===user.id} onClick={()=>setEditor(u)}><Edit3 size={13}/>Manage</Button></td></tr>)}</tbody></table></div></ResourceState></Panel><p className="fine-print">Changes affect the user’s authorized access. Your own account cannot be edited from this table.</p><RecoveryMailbox/>{editor?<EntityEditor title={`Manage ${editor.name}`} path="/admin/users" fields={fields} item={editor} onClose={()=>setEditor(null)} onSaved={resource.reload} notify={notify}/>:null}{createOpen?<CreateMember teams={teams.data} onClose={()=>setCreateOpen(false)} onSaved={resource.reload} notify={notify}/>:null}</>;
}
function CreateMember({teams,onClose,onSaved,notify}){
  const [form,setForm]=useState({name:'',email:'',password:'',district:'Ernakulam',role:'response_team',team_id:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');const set=(k,v)=>setForm(p=>({...p,[k]:v}));
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api('/admin/users',{method:'POST',body:{...form,team_id:form.team_id?Number(form.team_id):null}});notify('Team member account created.');onSaved();onClose();}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <Modal title="Add a response team member" onClose={onClose}><form onSubmit={submit}><Field label="Full name" required minLength={2} value={form.name} onChange={e=>set('name',e.target.value)} maxLength={120}/><Field label="Email" type="email" required value={form.email} onChange={e=>set('email',e.target.value)}/><Field label="Initial password" required type="password" minLength={10} value={form.password} onChange={e=>set('password',e.target.value)} autoComplete="new-password" hint="At least 10 characters. Share with the account owner securely."/><Select label="District" options={districts} value={form.district} onChange={e=>set('district',e.target.value)}/><Select label="Team" placeholder="Choose a team" required options={teams.map(t=>({value:t.id,label:t.name}))} value={form.team_id} onChange={e=>set('team_id',e.target.value)}/><ErrorNotice message={error}/><FormActions label="Create member account" onCancel={onClose} busy={busy}/></form></Modal>;
}
function RecoveryMailbox() {
  const [open,setOpen]=useState(false),resource=useData(open?'/admin/recovery-mail':null);
  return <Panel title="Private account recovery mailbox" subtitle="Administrator-only local delivery sink. Share recovery links privately with the verified account owner."><Button variant="secondary small" onClick={()=>{setOpen(true);resource.reload();}}>Open private recovery mailbox</Button>{open?<ResourceState resource={resource} emptyTitle="No recovery messages"><div className="request-list">{resource.data.map(message=><article className="field-finding" key={message.id}><strong>{message.recipient||message.email||message.to}</strong><p>{message.subject||'Password recovery requested'} · {date(message.created_at||message.delivered_at)}</p>{message.reset_url?<a className="text-button" href={message.reset_url} target="_blank" rel="noreferrer">Open private recovery link</a>:<span className="muted">Recovery message delivered by the configured email service.</span>}</article>)}</div></ResourceState>:null}</Panel>;
}

